### ISSUE TITLE
Minor issues with merged histologies

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/d3b-bixu-data-assembly#11] opened 2022-01-19 16:28 UTC
Updating this ticket with the latest histologies:

There are some minor issues with the merged histologies file that we can discuss in the next toolkit meeting. Using the latest merged histologies from the data assembly project:

1. Duplicate rows corresponding to `Kids_First_Biospecimen_ID`. For each of these duplicated rows, one row has `NA` and one row is properly populated for certain fields. 

```
dat <- read.delim('~/Downloads/tumor-board-1022-histology-ops-BS_ST7KGV85.tsv')
length(unique(dat$Kids_First_Biospecimen_ID)) # 36829 unique BS ids
dim(dat) # 39814 number of total rows

# one example is BS_007JTNB8 where the first row has NA for fields like cns_region, short_histology, etc but second row is properly populated 
> dat %>%
+     filter(Kids_First_Biospecimen_ID == "BS_007JTNB8")
  Kids_First_Biospecimen_ID      cns_region sample_id aliquot_id Kids_First_Participant_ID
1               BS_007JTNB8            <NA> 7316-2558     655073               PT_1MW98VR1
2               BS_007JTNB8 Posterior fossa 7316-2558     655073               PT_1MW98VR1
  experimental_strategy sample_type  composition  tumor_descriptor               primary_site
1                   WGS       Tumor Solid Tissue Initial CNS Tumor Cerebellum/Posterior Fossa
2                   WGS       Tumor Solid Tissue Initial CNS Tumor Cerebellum/Posterior Fossa
  reported_gender  race              ethnicity age_at_diagnosis_days pathology_diagnosis
1            Male White Not Hispanic or Latino                  1872          Ependymoma
2            Male White Not Hispanic or Latino                  1872          Ependymoma
  integrated_diagnosis short_histology broad_histology Notes germline_sex_estimate RNA_library
1                 <NA>            <NA>            <NA>  <NA>                  <NA>        <NA>
2                 <NA> Ependymal tumor Ependymal tumor  <NA>                  Male        <NA>
  OS_days OS_status PFS_days cohort age_last_update_days seq_center normal_fraction
1     687    LIVING      687   CBTN                 2559  NantOmics       0.3224044
2     687    LIVING      687   PBTA                 2559  NantOmics       0.3224044
  tumor_fraction tumor_ploidy cancer_predispositions     molecular_subtype cohort_participant_id
1      0.6775956            2        None documented                  <NA>               C632220
2      0.6775956            2        None documented EPN, To be classified               C632220
   extent_of_tumor_resection
1 Gross/Near total resection
2 Gross/Near total resection
```

2. RNA sample info for many samples is not available so have to pull it from warehouse and add to master histology file

```
# an example with patient 47, 48 and 49
dat %>%
  filter(cohort_participant_id %in% c("C3507468", "C3507591", "C3507714")) %>%
  dplyr::select(cohort_participant_id, experimental_strategy) %>%
  unique()

  cohort_participant_id experimental_strategy
1              C3507714                   WXS
2              C3507591                   WXS
3              C3507468                   WXS
```

3. `short_histology` info missing for many samples

```
# an example with patient 47, 48 and 49
dat %>%
  filter(cohort_participant_id %in% c("C3507468", "C3507591", "C3507714")) %>%
  dplyr::select(cohort_participant_id, short_histology) %>%
  unique()

  cohort_participant_id short_histology
1              C3507714            <NA>
2              C3507591            <NA>
3              C3507468            <NA>
```

4. For RNA samples that are present in the master histology file, there are 189 samples with no `RNA_library` info

```
# ids where RNA_library is NA
unique_bs_ids <- dat %>%
  filter(sample_type == "Tumor",
         experimental_strategy == "RNA-Seq",
         is.na(RNA_library)) %>%
  pull(Kids_First_Biospecimen_ID) %>%
  unique()

# 188 are from CBTN and 1 from GMKF
dat %>%
  filter(Kids_First_Biospecimen_ID %in% unique_bs_ids) %>%
  group_by(cohort)  %>%
  summarise(n = n())

# A tibble: 2 × 2
  cohort     n
  <chr>  <int>
1 CBTN     188
2 GMKF       1
```

5. Couple of 008 patient missing. We don't have data for 1, 7 and 50 so we can ignore those but we do have data for 43 and 44 and these patients do not seem to be present in the master histology file:

```
# latest data assembly histology file
dat = read.delim('tumor-board-1022-histology-ops-BS_ST7KGV85.tsv')

# pnoc008 clinical data manifest from Kids First data tracker
pnoc008_manifest = read_xlsx('FV_D8H9K61X_Copy of 03.01.2022 PNOC008 Clinical Data Manifest.xlsx', sheet = 2)

# identify ids that are in clinical data manifest but not in data assembly histology file
pnoc008_ids <- pnoc008_manifest$`Research ID`
pnoc008_not_found <- setdiff(pnoc008_ids, dat$cohort_participant_id)
pnoc008_manifest[which(pnoc008_manifest$`Research ID` %in% pnoc008_not_found),"PNOC Subject ID"]

# A tibble: 5 × 1
  `PNOC Subject ID`
  <chr>            
1 P-01             
2 P-07             
3 P-43             
4 P-44             
5 P-50 
```

cc: @aadamk

**Comment by aadamk** [comment] 2022-03-11 14:46
Hi @zhangb1 - can you look into what may be driving the BS-id duplication (issue 1) and missing RNAseq samples (issue 2) in the master histology file?

Issue 3 will require mapping code either at the level of the cwl pipeline or SQL mapping from ADAPT (will make a separate ticket for that). 

@zhangb1 - is it possible that issue 4 is likely due to missing info further upstream (e.g. are these values missing for those samples in the data service as well)?

Issue 5 - patients 1 and 7 were deemed ineligible for the trial, so it is expected that they would not be included in the master file. Patients 43 and 44 may just simply have been missed because I believe they were enrolled as we were transitioning to the cwl data assembly workflow - can you confirm that this is the reason @zhangb1 (and not due to a bug in the pipeline code)? 

@yuankunzhu - would Xiaoyan also be a point person to weigh in on these histologies issues as well?

**Comment by zhangb1** [comment] 2022-03-11 15:06
@aadamk  Thanks for the comments!

@komalsrathi  do you need the histology file  like `tumor-board-1022-histology-ops-*.tsv` for your analysis?  I thought you would get the histology file from Nick?  This **tumor-board-1022-histology-ops-*.tsv** is the file I made **ONLY**  for N+1 data assembly in the DNA data assembly task, which I only added The WGS Tumor information in the histology file along with the tumor ploidy , and tumor/normal fraction etc... Since RNAseq data assembly don't need the histology file , I usually skip the RNAseq sample for the propose.   

I think  we may need to have a short meeting for the discussion, happy to share the thoughts.

**Comment by komalsrathi** [comment] 2022-03-11 15:45
Hi @zhangb1 yes. We would need a master histologies file that has information on all RNA/DNA samples that are merged in the master genomics files (snvs, expression, cnvs).

**Comment by komalsrathi** [comment] 2022-03-28 17:19
```
#  what cohorts correspond to duplicated BS ids
tmp = dat %>%
  group_by(Kids_First_Biospecimen_ID) %>%
  summarise(n = n(),
         cohort = toString(cohort)) %>%
  filter(n > 1) 
plyr::count(tmp$cohort)

           x freq
1 CBTN, CBTN    1
2 CBTN, PBTA 2680
3 PNOC, PBTA  304

# the CBTN, CBTN BS id is BS_J9K1Y535
```

**Comment by aadamk** [comment] 2022-03-28 17:26
Thanks all for the meeting. 
Capturing key action items here:
- Duplication issue (issues 1 and 4): per @zhangb1, this is a result of cohort designations - a subset of samples may be double-listed as CBTN/PBTA or PNOC/PBTA - designating only as PBTA will remove duplication. 
- RNAseq missing data (issue 2): Miguel to review [cwltools PR](https://github.com/d3b-center/d3b-bixu-data-assembly/pull/10) and merge.
- Issue 3: need ADAPT to implement short and broad histology mapping using the bix-processed master histologies file. 
- Issue 5: per @zhangb1, re-running monthly release should resolve. For toolkit, running as a real-time +1 workflow would support the tumor board, so the plan is to discuss this strategy with Yuankun.

**Comment by zhangb1** [comment] 2022-03-29 18:59
Sorry @aadamk  Please use this one, I think the issue is the tsv file opened in xlsx before , the format got changed. 
This file will fix the issue. 
[histologies-add-bixops-uptoPNOC008-50.tsv.gz](https://github.com/d3b-center/d3b-bixu-data-assembly/files/8374244/histologies-add-bixops-uptoPNOC008-50.tsv.gz)

**Comment by aadamk** [comment] 2022-03-30 14:11
Great, thanks. looks like the major issues are addressed (duplication, missing 008 subjects, missing rna samples). short_histology and molecular_subtyping annotations can be resolved in other tickets. 

@komalsrathi - do you think this can be closed?

**Closed** 2022-03-30 15:02 UTC

**Comment by jharenza** [comment] 2022-05-06 00:58
just commenting on here that @nicholasvk has fixed the duplication issue with the PNOC samples per https://github.com/PediatricOpenTargets/ticket-tracker/issues/306 cc @yuankunzhu @aadamk
